# Generated by Django 6.0.5 on 2026-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_organization_user_phone_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('friend_request', '好友申请'), ('friend_accepted', '好友申请通过'), ('new_message', '新消息'), ('group_created', '建群通知'), ('group_invite', '群聊邀请'), ('system', '系统通知')], max_length=32),
        ),
    ]
