# Generated by Django 6.0.5 on 2026-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('online', '在线'), ('away', '忙碌'), ('dnd', '请勿打扰'), ('offline', '离线')], default='offline', max_length=16),
        ),
    ]
