# Generated by Django 6.0.5 on 2026-06-09 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': '会话', 'verbose_name_plural': '会话'},
        ),
        migrations.AlterModelOptions(
            name='conversationmember',
            options={'verbose_name': '会话成员', 'verbose_name_plural': '会话成员'},
        ),
        migrations.AlterModelOptions(
            name='conversationreadstate',
            options={'verbose_name': '已读状态', 'verbose_name_plural': '已读状态'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='已归档'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'direct'), ('group', 'group')], max_length=16, verbose_name='会话类型'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.conversation', verbose_name='会话'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=16, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='conversationreadstate',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.conversation', verbose_name='会话'),
        ),
        migrations.AlterField(
            model_name='conversationreadstate',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后阅读时间'),
        ),
        migrations.AlterField(
            model_name='conversationreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_read_states', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='附件名称'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='附件类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='附件地址'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='所属会话'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='message',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_messages', to=settings.AUTH_USER_MODEL, verbose_name='撤回者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
