# Generated by Django 6.0.5 on 2026-06-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('archive', '归档总结')], default='archive', max_length=32, verbose_name='总结类型')),
                ('content', models.TextField(verbose_name='总结内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='chat.conversation', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': '聊天总结',
                'verbose_name_plural': '聊天总结',
                'ordering': ['-created_at'],
            },
        ),
    ]
