# Generated by Django 6.0.5 on 2026-06-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='附件类型'),
        ),
    ]
