# Generated by Django 6.0.5 on 2026-06-11 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('report_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('archive_summary', '归档总结'), ('user_doc', '我的文档')], default='daily', max_length=32, verbose_name='报告类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(choices=[('report_generator', '报告生成器'), ('group_archive', '群聊归档'), ('user_save', '用户保存')], default='report_generator', max_length=32, verbose_name='来源')),
                ('related_conv_id', models.IntegerField(blank=True, null=True, verbose_name='关联会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '保存的报告',
                'verbose_name_plural': '保存的报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
