# Generated by Django 6.0.5 on 2026-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
