# Generated by Django 6.0.5 on 2026-06-09 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '事件', 'verbose_name_plural': '事件'},
        ),
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'verbose_name': '事件群组', 'verbose_name_plural': '事件群组'},
        ),
        migrations.AlterField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('pre_sales', '售前事件'), ('in_sales', '售中事件'), ('after_sales', '售后事件'), ('custom', '自定义')], default='custom', max_length=32, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='open', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='已归档'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_group', to='chat.conversation', verbose_name='群聊'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='events.event', verbose_name='事件'),
        ),
    ]
