# Generated by Django 6.0.5 on 2026-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventgroup_options_and_more'),
        ('members', '0008_add_tag_task_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='members.tag', verbose_name='标签'),
        ),
    ]
